Homework-1
MukhametDev/2024-2-VK-EDU-Frontend-M-Zhanbekov pull request #1
Opened 2024-10-09 19:32 UTC by MukhametDev

Выполненная домашняя работа №1

2024-10-09 19:55 UTC, martinkomitsky commented
В шаблоне PR не указаны Кирилл и ментор

2024-10-09 20:02 UTC, MukhametDev commented
> В шаблоне PR не указаны Кирилл и ментор

Исправил

2024-10-09 20:02 UTC, martinkomitsky commented
> > В шаблоне PR не указаны Кирилл и ментор
> 
> Исправил
Еще вот это, плз
https://github.com/MukhametDev/vk-app/issues/2

2024-10-09 20:05 UTC, martinkomitsky commented
надо добавить файл с шаблоном для PR из инструкции

2024-10-09 20:07 UTC, MukhametDev commented
> > > В шаблоне PR не указаны Кирилл и ментор
> > 
> > 
> > Исправил
> 
> Еще вот это, плз #2

Тоже вроде поправил

2024-10-09 20:12 UTC, MukhametDev commented
> надо добавить файл с шаблоном для PR из инструкции

Сделано!

2024-10-10 10:07 UTC, sh4rkizz requested changes
Давай поправим тесты

2024-10-10 10:07 UTC, sh4rkizz commented on convertBytesToHuman.test.js
> +  });
Стоит так же проверить на NaN, Infinite, -Infinite
Что-то из этого точно не пройдет

2024-10-10 11:18 UTC, sh4rkizz approved these changes
lgtm

2024-10-10 12:43 UTC, merged

2024-10-10 12:43 UTC, martinkomitsky commented
7