ДЗ 2
MukhametDev/2024-2-VK-EDU-Frontend-M-Zhanbekov pull request #3
Opened 2024-10-09 19:56 UTC by MukhametDev

# Домашнее задание №2

Прошу @martinkomitsky  и @sh4rkizz проверить его.

Что было сделано:
*Верстка сайта согласно макету
*Подключение и  написание стилей 
*Написание функционала на js

2024-10-09 20:04 UTC, martinkomitsky commented
> # Домашнее задание №2
> Прошу @martinkomitsky и @sh4rkizz проверить его.


и тут всех менторов поправить

2024-10-09 20:19 UTC, MukhametDev commented
> > # Домашнее задание №2
> > Прошу @martinkomitsky и @sh4rkizz проверить его.
> 
> и тут всех менторов поправить

Обновил

2024-10-10 10:16 UTC, sh4rkizz requested changes
Давай поправим и будет бомба

2024-10-10 10:16 UTC, sh4rkizz commented on src/index.js
> +    });
Этот ивент тебе не нужен, поскольку он ререндерит страницу при отправке сообщения [что выбрасывает на 404]

Предлагаю спилить, поскольку нажатие на Enter обслуживается формами браузера по умолчанию [при наличии фокуса в них]

Однано для этого нужно вернуть этот участок кода [с доработкой]
form.addEventListener('submit', handleSubmit);

2024-10-10 10:16 UTC, sh4rkizz commented on src/index.html
> +    <header class="header">
Давай уменьшим высоту хедера, сейчас она очень большой кажется
\+ Предлагаю так же стилизовать блоки сообщений, чтобы они больше походили на мобилный чат

<img width="765" alt="изображение" src="https://github.com/user-attachments/assets/45c216aa-3714-45ea-90ce-6ddc0693fede">

2024-10-10 10:16 UTC, sh4rkizz commented on src/index.html
> +    <header class="header">
Давай вынесем инонку прикрепления файла за элемент ввода текста, чтобы не перекрывалось, когда сообщение длинное

<img width="738" alt="изображение" src="https://github.com/user-attachments/assets/015f88d1-e1bb-46e1-88c0-0fb9ab0b6794">

2024-10-10 10:16 UTC, sh4rkizz commented on src/index.html
> +    <header class="header">
А также стилизуем [если будешь делать блоки] максимальную длину сообщения, чтобы его текст сносился вниз, а не вылезал за границу блока

<img width="842" alt="изображение" src="https://github.com/user-attachments/assets/c91c5160-e824-4bf7-8c18-dde8fb07af6a">

2024-10-10 12:45 UTC, martinkomitsky submitted a review, later dismissed
После мержа 1 дз тут конфликт. Надо поправить

2024-10-17 14:02 UTC, sh4rkizz requested changes
пара замечаний, стоит поправить, чтобы легче было перейти к 3 домашке

2024-10-17 14:02 UTC, sh4rkizz commented on src/index.js
> +    }
Стоит стилизовать сообщения
например так, чтобы мои сообщения отображались с правой стороны, а не располагались по центру, 
а сообщения собеседника [которые попрошу доработать в третьей домашке] - с левой


![изображение](https://github.com/user-attachments/assets/a4919b53-3a72-42ab-afd8-ba3a0e55ccde)

2024-10-17 14:02 UTC, sh4rkizz commented on src/index.js
> +    }
фон на кнопке отправки кажется лишним, она и так довольно заметна, предлагаю убрать
![изображение](https://github.com/user-attachments/assets/fc1b8ffd-dee5-41c6-b3a6-d503511f999b)

2024-10-27 18:15 UTC, martinkomitsky commented
@MukhametDev привет! понимаю, много тут накидали комментов. Получится добить в ближайшее время?

2024-10-28 05:36 UTC, MukhametDev commented
> @MukhametDev привет! понимаю, много тут накидали комментов. Получится добить в ближайшее время?

Я постараюсь за сегодня или завтра закончить

2024-10-29 20:39 UTC, MukhametDev commented
> @MukhametDev привет! понимаю, много тут накидали комментов. Получится добить в ближайшее время?

@martinkomitsky, замечания исправил

2024-10-29 20:56 UTC, sh4rkizz approved these changes
lgtm

2024-10-31 06:40 UTC, HaseProgram approved these changes
7!

2024-10-31 06:40 UTC, merged